export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const ADD_API_DATA = 'ADD_API_DATA';
export const GET_TRAILER = 'GET_TRAILER';
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const GET_WEEK_TRENDING = 'GET_WEEK_TRENDING';