export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const ADD_API_DATA = 'ADD_API_DATA';
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const GET_WEEK_TRENDING = 'GET_WEEK_TRENDING';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DATAILS';
export const SET_AUTO_COMPLETION = 'SET_AUTO_COMPLETION';
export const EMPTY_AUTO_COMPLETION = 'EMPTY_AUTO_COMPLETION';